
import { Country } from './types.ts';

export const CONTINENTS = [
  'Africa',
  'Antarctica',
  'Asia',
  'Europe',
  'North America',
  'Oceania',
  'South America'
];

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: 'AF', continent: 'Asia' },
  { name: 'Albania', code: 'AL', continent: 'Europe' },
  { name: 'Algeria', code: 'DZ', continent: 'Africa' },
  { name: 'Argentina', code: 'AR', continent: 'South America' },
  { name: 'Australia', code: 'AU', continent: 'Oceania' },
  { name: 'Austria', code: 'AT', continent: 'Europe' },
  { name: 'Bangladesh', code: 'BD', continent: 'Asia' },
  { name: 'Belgium', code: 'BE', continent: 'Europe' },
  { name: 'Bolivia', code: 'BO', continent: 'South America' },
  { name: 'Brazil', code: 'BR', continent: 'South America' },
  { name: 'Bulgaria', code: 'BG', continent: 'Europe' },
  { name: 'Cambodia', code: 'KH', continent: 'Asia' },
  { name: 'Cameroon', code: 'CM', continent: 'Africa' },
  { name: 'Canada', code: 'CA', continent: 'North America' },
  { name: 'Chile', code: 'CL', continent: 'South America' },
  { name: 'China', code: 'CN', continent: 'Asia' },
  { name: 'Colombia', code: 'CO', continent: 'South America' },
  { name: 'Costa Rica', code: 'CR', continent: 'North America' },
  { name: 'Croatia', code: 'HR', continent: 'Europe' },
  { name: 'Cuba', code: 'CU', continent: 'North America' },
  { name: 'Czech Republic', code: 'CZ', continent: 'Europe' },
  { name: 'Denmark', code: 'DK', continent: 'Europe' },
  { name: 'Egypt', code: 'EG', continent: 'Africa' },
  { name: 'Estonia', code: 'EE', continent: 'Europe' },
  { name: 'Ethiopia', code: 'ET', continent: 'Africa' },
  { name: 'Finland', code: 'FI', continent: 'Europe' },
  { name: 'France', code: 'FR', continent: 'Europe' },
  { name: 'Germany', code: 'DE', continent: 'Europe' },
  { name: 'Greece', code: 'GR', continent: 'Europe' },
  { name: 'Hungary', code: 'HU', continent: 'Europe' },
  { name: 'Iceland', code: 'IS', continent: 'Europe' },
  { name: 'India', code: 'IN', continent: 'Asia' },
  { name: 'Indonesia', code: 'ID', continent: 'Asia' },
  { name: 'Iran', code: 'IR', continent: 'Asia' },
  { name: 'Iraq', code: 'IQ', continent: 'Asia' },
  { name: 'Ireland', code: 'IE', continent: 'Europe' },
  { name: 'Israel', code: 'IL', continent: 'Asia' },
  { name: 'Italy', code: 'IT', continent: 'Europe' },
  { name: 'Japan', code: 'JP', continent: 'Asia' },
  { name: 'Jordan', code: 'JO', continent: 'Asia' },
  { name: 'Kazakhstan', code: 'KZ', continent: 'Asia' },
  { name: 'Kenya', code: 'KE', continent: 'Africa' },
  { name: 'South Korea', code: 'KR', continent: 'Asia' },
  { name: 'Malaysia', code: 'MY', continent: 'Asia' },
  { name: 'Mexico', code: 'MX', continent: 'North America' },
  { name: 'Morocco', code: 'MA', continent: 'Africa' },
  { name: 'Netherlands', code: 'NL', continent: 'Europe' },
  { name: 'New Zealand', code: 'NZ', continent: 'Oceania' },
  { name: 'Nigeria', code: 'NG', continent: 'Africa' },
  { name: 'Norway', code: 'NO', continent: 'Europe' },
  { name: 'Pakistan', code: 'PK', continent: 'Asia' },
  { name: 'Peru', code: 'PE', continent: 'South America' },
  { name: 'Philippines', code: 'PH', continent: 'Asia' },
  { name: 'Poland', code: 'PL', continent: 'Europe' },
  { name: 'Portugal', code: 'PT', continent: 'Europe' },
  { name: 'Romania', code: 'RO', continent: 'Europe' },
  { name: 'Russia', code: 'RU', continent: 'Europe' },
  { name: 'Saudi Arabia', code: 'SA', continent: 'Asia' },
  { name: 'Singapore', code: 'SG', continent: 'Asia' },
  { name: 'South Africa', code: 'ZA', continent: 'Africa' },
  { name: 'Spain', code: 'ES', continent: 'Europe' },
  { name: 'Sweden', code: 'SE', continent: 'Europe' },
  { name: 'Switzerland', code: 'CH', continent: 'Europe' },
  { name: 'Taiwan', code: 'TW', continent: 'Asia' },
  { name: 'Thailand', code: 'TH', continent: 'Asia' },
  { name: 'Turkey', code: 'TR', continent: 'Asia' },
  { name: 'Ukraine', code: 'UA', continent: 'Europe' },
  { name: 'United Kingdom', code: 'GB', continent: 'Europe' },
  { name: 'United States', code: 'US', continent: 'North America' },
  { name: 'Vietnam', code: 'VN', continent: 'Asia' }
];
